import csv

data = [
    ("2r", "Devil’s dung / Giant Fennel", "Ferula foetida"),
    ("2v", "Water Lily", "Nymphaea odorata"),
    ("3r", "Salvia / Garden Sage", "Salvia officinalis"),
    ("8v", "Bugloss", "Anchusa officinalis"),
    ("14r", "Sorrel", "Rumex acetosa"),
    ("15v", "Herb Paris", "Paris quadrifolia"),
    ("20r", "Pennyroyal", "Mentha pulegium"),
    ("21r", "Thyme", "Thymus vulgaris"),
    ("25r", "Lemon Balm", "Melissa officinalis"),
    ("31r", "Siderica", "Unknown"),
    ("31v", "Fennel", "Foeniculum vulgare"),
    ("35r", "Unknown", "Unknown"),
    ("35v", "English Ivy", "Hedera helix"),
    ("36r", "Larkspur", "Delphinium"),
    ("36v", "Henbit", "Lasmium"),
    ("37v", "Mint", "Menthe"),
    ("41r", "Oregano / Marjoram", "Origamum vulgare"),
    ("44v", "Italian Parsley", "Petroselinum crispun"),
    ("47r", "Houseleek", "Sempervivum tectorum"),
    ("49v", "Water Lily", "Nymphaea alba"),
    ("52v", "Heliotrope", "Heliopropium"),
    ("53v", "Hawkweed", "Hieracium aurantiaca"),
    ("55v", "Unknown", "Unknown"),
    ("87v", "Cowslip / Primrose", "Primula veris"), # 87vleft
    ("1v", "Herba orbicularis / Deadly Nightshade", "Aristrolochia pallida / Atropa belladonna"), # Conflict in source, kept both
    ("4r", "Alpine Saxifrage", "Saxifraga cespitosa"),
    ("5v", "Mallow", "Malva sylvestris"),
    ("6r", "Bear Breeches", "Acanthus mollis"),
    ("6v", "Caster Oil", "Ricinus communis"),
    ("7v", "Madder", "Rubia tinctorun"),
    ("10r", "Chicory / Endive", "Cichorium pumilum"),
    ("11r", "Rosemary", "Rosmarinus officinalis"),
    ("14v", "Betony", "Stachys officinalis"),
    ("15r", "Sow Thistles", "Sonchus oleraceus"),
    ("16r", "Cannabis", "Cannabis sativa"),
    ("17r", "Swallowwort", "Unknown"),
    ("17v", "Smilex", "Smilax"),
    ("18v", "Columbine", "Aquilegia alpina"),
    ("20v", "Carduus Thistle", "Cirsium"),
    ("23v", "Borage", "Borago officinalis"),
    ("24r", "Squash / Cucumber", "Cucurbita"),
    ("24v", "Botris", "Unknown"),
    ("26r", "Wormwood", "Artemesia absinthium"),
    ("26v", "Horsetail", "Equisetum"),
    ("27r", "Meadow Sage", "Salvia pratensis"),
    ("27v", "Clove", "Syzyglum aromaticum"),
    ("28r", "Plantago Major", "Plantago major"),
    ("28v", "Rhododendron", "Rhododendron"),
    ("29r", "Lettuce", "Lactuce sativa"),
    ("29v", "Roman Coriander", "Nigella sativa"),
    ("30r", "Comfrey", "Symphytum officinale"),
    ("30v", "Bay Laurel", "Laurus nobilis"),
    ("32r", "Speedwell", "Veronica officinalis"),
    ("32v", "Tormentil", "Tormentilla erecta"),
    ("33v", "Winter Aconite", "Eranthis heymalis"),
    ("34r", "Ox-eye Daisy", "Callilepis laureola"),
    ("34v", "Devil’s Weed", "Tribulus terrestris"),
    ("38r", "Opium Poppy", "Papaver somniferum"),
    ("39r", "Wallflower", "Erysimum"),
    ("40v", "Unknown", "Unknown"),
    ("41v", "Coriander", "Coriandrum sativum"),
    ("42r", "Wood Sorrel", "Oxalis acetosella"),
    ("43v", "Wild Oats", "Avena sterilis"),
    ("44r", "Mandrake", "Mandragora officinarum"),
    ("45r", "Orach", "Atriplex hortensis"),
    ("46r", "Unknown", "Unknown"),
    ("47v", "Lungwort", "Pulmonaria officinalis"),
    ("48v", "Celandine", "Chelidonium majus"),
    ("51v", "Millet", "Setaria italica"),
    ("52r", "Lovage", "Levisticum officinale"),
    ("53r", "Herb Christopher", "Actaea spicata"),
    ("54r", "Creeping Thistle", "Circium arvense"),
    ("54v", "Sage", "Salvia officinalis"),
    ("55r", "Fumitory", "Fumaria officinalis"),
    ("57r", "Lady’s Mantle", "Alchemilla vulgaris"),
    ("65r", "Larkspur", "Delphinium"),
    ("65v", "Cornflower", "Centaurea cyanus"),
    ("66v", "Bay Laurel", "Laurus nobilis"),
    ("87r", "Aloe", "Aloe vera"),
    ("90r2", "Chervil", "Arthriscus cerefolium"),
    ("90v1", "Arugula", "Eruca vesicaria"),
    ("93v", "Switch Grass", "Panicum"),
    ("94r", "Moonwort", "Botrychium lunaria"),
    ("95v2", "Apium silvestre", "Unknown"),
    ("96r", "Black Hellebore", "Helleborus niger"),
    ("96v", "Black Byrony", "Tamus communis"),
    ("3v", "Dungwort", "Helleborus foetidus"),
    ("4v", "European Bellflower", "Campanula"),
    ("5r", "Wolf's Bane", "Arnica montana"),
    ("7r", "Bog Stichwort", "Stellaria alsine"),
    ("8r", "Green Pea", "Pisum sativum"),
    ("9r", "Ragweed", "Ambrosia"),
    ("9v", "Heartsease", "Viola tricolor"),
    ("10v", "Twinflower", "Linnaea borealis"),
    ("11v", "Rhodiola", "Rhodiola rosea"),
    ("13r", "Banana", "Musa"),
    ("13v", "Honeysuckle", "Lonicera periclymenum"),
    ("16v", "Chrysanthemum", "Chrysanthemum"),
    ("18r", "Alpine Daisy", "Aster amellus"),
    ("19r", "Greek Valerian", "Polemonium caeruleum"),
    ("19v", "Nailwort", "Draba nivalis"),
    ("21v", "Burning Bush", "Dictamnus albus"),
    ("22r", "Common Vervain", "Verbena officinalis"),
    ("22v", "Tulip", "Tulipa"),
    ("23r", "Pasque Flower", "Pulsatilla vulgaris"),
    ("25v", "Woad", "Isatis tinctoria"),
    ("33r", "Gentiana", "Gentiana verna"),
    ("37r", "Foxglove", "Digitalis purpura"),
    ("38v", "Stonecrops", "Sedum anacampseros"),
    ("39v", "Ragwort", "Senecio vulgaris"),
    ("40r", "Primula", "Primula minima"),
    ("42v", "Columbine", "Aqulegia vulgaris"),
    ("43r", "Alpine Balsum", "Erinus alpinus"),
    ("45v", "Lavender", "Lavendula officinulis"),
    ("46v", "Ploughman’s Spikenard", "Inula conyza"),
    ("48r", "False Hellebore", "Adonis vernalis"),
    ("49r", "Blue Nile Lotus", "Nymphaea caerulea"),
    ("50r", "Masterwort", "Astrantia major"),
    ("50v", "Soldanella", "Soldanella pulsitilla"),
    ("51r", "European Searocket", "Cakile maritima"),
    ("56r", "Round Leaf Sundew", "Drosera rotundifolia"),
    ("56v", "Sago Palm", "Cycas revoluta"),
    ("87v_right", "Lousewort", "Pedicularis flammea"),
    ("90v2", "Tansy", "Tanacetum vulgare"),
    ("93r", "Artichoke", "Cynara cardunculus"),
    ("94v", "Rose Campion", "Lychnis coronaria"),
    ("95r1", "Alpine Bayberry", "Arctostaphylos alpina"),
    ("95v1", "Hollyhock", "Alcea"),
    ("95r2", "Ribwort", "Plantago lanceolata")
]

with open('data/external_corpora/sherwood_plant_mapping.csv', 'w', newline='') as f:
    writer = csv.writer(f)
    writer.writerow(['Folio', 'Common Name', 'Latin Name'])
    writer.writerows(data)

print(f"Created mapping with {len(data)} entries.")
