import random
from collections import defaultdict, Counter
from research.voynich_data import get_eva_pages

OUTPUT_FILE = "results/markov_comparison.md"

def train_markov(text, order=2):
    model = defaultdict(Counter)
    words = text.split()
    for i in range(len(words) - order):
        state = tuple(words[i:i+order])
        next_word = words[i+order]
        model[state][next_word] += 1
    return model

def generate_text(model, length=1000, order=2):
    # Start with a random state
    state = random.choice(list(model.keys()))
    output = list(state)
    
    for _ in range(length):
        if state not in model: break
        # Weighted random choice
        next_word = random.choices(
            list(model[state].keys()),
            weights=model[state].values()
        )[0]
        output.append(next_word)
        state = tuple(output[-order:])
    
    return " ".join(output)

def calculate_stats(text):
    words = text.split()
    counts = Counter(words)
    
    # Zipf slope approximation (log-log fit)
    # Simplify: Just return top 10 frequencies
    top_10 = [c for w, c in counts.most_common(10)]
    
    # Repeat rate (immediate repeats)
    repeats = sum(1 for i in range(len(words)-1) if words[i] == words[i+1])
    repeat_rate = repeats / len(words) if words else 0
    
    return {
        "unique_words": len(counts),
        "total_words": len(words),
        "ttr": len(counts)/len(words) if words else 0, # Type-Token Ratio
        "repeat_rate": repeat_rate,
        "top_counts": top_10
    }

def main():
    print("Loading Voynich...")
    pages = get_eva_pages()
    # Split into Train (First 50%) and Test (Second 50%)
    all_folios = sorted(pages.keys())
    mid = len(all_folios) // 2
    
    train_folios = all_folios[:mid]
    test_folios = all_folios[mid:]
    
    train_text = " ".join([" ".join(pages[f].values()) for f in train_folios])
    test_text = " ".join([" ".join(pages[f].values()) for f in test_folios])
    
    print(f"Training Markov Model (Order 2) on {len(train_text)} chars...")
    model = train_markov(train_text, order=2)
    
    print("Generating Fake Voynich...")
    # Generate roughly same length as test set
    target_len = len(test_text.split())
    fake_text = generate_text(model, length=target_len)
    
    print("Calculating Statistics...")
    real_stats = calculate_stats(test_text)
    fake_stats = calculate_stats(fake_text)
    
    report = [
        "# Markov Null Hypothesis Test",
        "",
        "Comparing the second half of the manuscript ('Real') with text generated by a Markov chain trained on the first half ('Fake').",
        "",
        "| Metric | Real Voynich (Test Set) | Fake Voynich (Markov) |",
        "|---|---|---|",
        f"| Total Words | {real_stats['total_words']} | {fake_stats['total_words']} |",
        f"| Unique Words | {real_stats['unique_words']} | {fake_stats['unique_words']} |",
        f"| Type-Token Ratio | {real_stats['ttr']:.4f} | {fake_stats['ttr']:.4f} |",
        f"| Repeat Rate | {real_stats['repeat_rate']:.4f} | {fake_stats['repeat_rate']:.4f} |",
        "",
        "## Interpretation",
        "- If **Repeat Rate** is significantly different, the Markov model fails to capture the 'echo' structure.",
        "- If **TTR** is different, the vocabulary growth is non-linear.",
        ""
    ]
    
    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write('\n'.join(report))
        
    print(f"Test complete. See {OUTPUT_FILE}")

if __name__ == "__main__":
    main()
