import json
import re
import os

# Load Dictionary
dict_path = 'results/root_dictionary_v1.json'
if not os.path.exists(dict_path):
    print(f"Error: {dict_path} not found.")
    exit(1)

with open(dict_path, 'r') as f:
    data = json.load(f)
    # Handle if roots are nested or direct
    if 'roots' in data:
        root_dict = data['roots']
    else:
        root_dict = data

# Translation Maps
TAG_MAP = {
    'VERB': '[Action]',
    'IMP': 'Take/Do',
    'CONJ': 'and',
    'NOUN': 'the'
}

PREFIX_MAP = {
    'qo': 'VERB',
    'daiin': 'IMP',
    'd': 'IMP',
    'y': 'CONJ',
    'o': 'NOUN'
}

# Sort prefixes by length desc (longest first)
SORTED_PREFIXES = sorted(PREFIX_MAP.keys(), key=len, reverse=True)

def translate_word(word):
    # Clean word (remove punctuation commonly found in EVA)
    # EVA uses . as separator, but sometimes ! or , exist
    clean_word = word.strip('!,.')
    if not clean_word:
        return ""
    
    prefix_found = None
    root = clean_word
    
    # Identify prefix
    for p in SORTED_PREFIXES:
        if clean_word.startswith(p):
            if clean_word == p:
                # Word IS the prefix
                prefix_found = p
                root = ""
                break
            else:
                # Word STARTS with prefix
                prefix_found = p
                root = clean_word[len(p):]
                break
    
    # Translate Prefix
    tag = PREFIX_MAP.get(prefix_found)
    tag_meaning = TAG_MAP.get(tag, "")
    
    # Translate Root
    root_meaning = ""
    if root:
        if root in root_dict:
            entry = root_dict[root]
            # entry might be a dict with 'meanings' or just the meaning?
            # Based on previous read: "meanings": ["earth"]
            meanings = entry.get('meanings', [])
            if meanings:
                root_meaning = meanings[0]
            else:
                root_meaning = root
        else:
            root_meaning = root
    
    # Format: [Tag Meaning] [Root Meaning]
    parts = []
    if tag_meaning:
        parts.append(tag_meaning)
    
    if root_meaning:
        # If we have a tag, capitalize the root to look like "Take Leaf"
        if tag_meaning:
            parts.append(root_meaning.title())
        else:
            parts.append(root_meaning)
            
    return " ".join(parts)

# Process Pages
# Target pages: diverse selection
target_pages = ['f1r', 'f20r', 'f33r', 'f68r', 'f77r', 'f82r', 'f88r', 'f95r', 'f105r', 'f112r']

page_content = {} # pid -> list of lines

data_path = 'data/eva_ivtff.txt'
if not os.path.exists(data_path):
    print(f"Error: {data_path} not found.")
    exit(1)

print("Reading data...")
with open(data_path, 'r') as f:
    for line in f:
        if line.startswith('<f'):
            # Example: <f1r.1,@P0;H>	fachys...
            # Regex to capture 'f1r' from '<f1r' or '<f1r.1'
            # The IVTFF format for page is <fXXX> or <fXXX.Y...>
            # So we match <(f[\w]+)
            match = re.match(r'<(f[\w]+)', line)
            if match:
                pid = match.group(1)
                
                if pid in target_pages:
                    # Only process transcription lines
                    if '\t' in line:
                        parts = line.strip().split('\t')
                        tag_part = parts[0]
                        text_part = parts[1] if len(parts) > 1 else ""
                        
                        # Filter for 'H' transcriber
                        if ';H>' in tag_part:
                             if pid not in page_content: page_content[pid] = []
                             page_content[pid].append(text_part)

print(f"Found content for {len(page_content)} pages.")

output_lines = []
output_lines.append("# Syntax Translation Sample")
output_lines.append("\nGenerated by mapping Tags (Prefixes) and Roots.")
output_lines.append("\n**Mapping Rules:**")
output_lines.append("- `qo-` -> [Action]")
output_lines.append("- `d-`/`daiin` -> Take/Do")
output_lines.append("- `y-` -> and")
output_lines.append("- `o-` -> the")
output_lines.append("\n---")

found_pages = sorted(page_content.keys(), key=lambda x: target_pages.index(x) if x in target_pages else 999)

for pid in found_pages:
    output_lines.append(f"\n## Page {pid}")
    lines = page_content[pid]
    
    for i, txt in enumerate(lines):
        # Tokenize
        words = txt.split('.')
        trans_words = [translate_word(w) for w in words if w.strip()]
        sentence = " ".join(trans_words)
        
        output_lines.append(f"\n**Line {i+1}:** `{txt}`")
        output_lines.append(f"> {sentence}")

# Write Output
out_path = 'results/syntax_translation_sample.md'
with open(out_path, 'w') as f:
    f.write('\n'.join(output_lines))

print(f"Output written to {out_path}")
